### PR TITLE
Add some missing blog posts

### PR DESCRIPTION
**Pull request by haydentherapper**
* BYO TUF
* Adopting Sigstore incrementally
* Fixing Dex vuln

Ref https://github.com/sigstore/sigstore-blog/issues/15

Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>

### CODE REVIEW

**Review by lukehinds — APPROVED** [review]

**Comment by lukehinds** [comment]
Good catch, I am concerned what others might be missing now.

**Comment by haydentherapper** [comment]
@lukehinds The issue linked in the PR contains the list, it’s about 15. I can’t view others though since medium.com/Sigstore redirects to the new blog

**Review by bobcallaway — APPROVED** [review]

**Comment by rchaganti** [comment]
Good catch. I looked at medium and migrated everything posted in Sigstore. I might have missed another filter.

**Comment by haydentherapper** [comment]
It’s likely these were all posts that were reposted by the Sigstore account but authored by others.

**Pull request merged**
