### PR TITLE
Add blog post to discuss timestamping

### PR DESCRIPTION
**Pull request by haydentherapper**
#### Summary

This discusses how to leverage a timestamp authority with Sigstore.

### CODE REVIEW

**Comment by haydentherapper** [comment]
/HOLD until there's a public link for a GitHub TSA

**Comment by haydentherapper** [comment]
Blog post is ready to go. TSC for approval: @bobcallaway @priyawadhwa @SantiagoTorres @lukehinds @trevrosen

**Review by bobcallaway — APPROVED** [review]

**Review by malancas — APPROVED** [review]

**Comment by hectorj2f** [comment]
lgtm, thanks @haydentherapper

**Comment by haydentherapper** [comment]
@lukehinds @priyawadhwa @trevrosen @SantiagoTorres ptal

**Review by priyawadhwa — APPROVED** [review]

**Review by SantiagoTorres — APPROVED** [review]

**Pull request merged**
