### PR TITLE
Update about page

### PR DESCRIPTION
**Pull request by haydentherapper**

### CODE REVIEW

**Comment by haydentherapper** [comment]
@vaikas, better now? :)

**Review by bobcallaway — DISMISSED** [review]

**Comment by haydentherapper** [comment]
Do you want me to remove "standard" based on the PR on sigstore-website?

**Comment by bobcallaway** [comment]
> Do you want me to remove "standard" based on the PR on sigstore-website?

that would be nice

**Comment by haydentherapper** [comment]
Done

**Review by bobcallaway — APPROVED** [review]

**Review by vaikas — APPROVED** [review]
It's better for sure, thank you :)

**Pull request merged**
